// Paths of Profile Pictures
export const AVATAR = [
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_2.png") },
];

export const ICON = {
  white: {
    remove: require("../../assets/icon/icn_remove_wh.png"),
    save: require("../../assets/icon/icn_save_wh.png"),
    add: require("../../assets/icon/icn_add_wh.png"),
    option: require("../../assets/icon/icn_option_wh.png"),
    close: require("../../assets/icon/icn_close_wh.png"),
    home: require("../../assets/icon/icn_home_wh.png"),
    settings: require("../../assets/icon/icn_settings_wh.png"),
    store: require("../../assets/icon/icn_store_wh.png"),
    toolbox: require("../../assets/icon/icn_toolbox_wh.png"),
    back: require("../../assets/icon/icn_back_wh.png"),
    more: require("../../assets/icon/icn_more_wh.png"),
    send: require("../../assets/icon/icn_send_wh.png"),
  },

  black: {
    edit: require("../../assets/icon/icn_edit_bl.png"),
    nav: require("../../assets/icon/icn_nav_bl.png"),
    play: require("../../assets/icon/icn_play_bl.png"),
    shuffle: require("../../assets/icon/icn_shuffle_bl.png"),
    loop: require("../../assets/icon/icn_loop_bl.png"),
    finished: require("../../assets/icon/icn_finished_bl.png"),
    home: require("../../assets/icon/icn_home_bl.png"),
    settings: require("../../assets/icon/icn_settings_bl.png"),
    store: require("../../assets/icon/icn_store_bl.png"),
    toolbox: require("../../assets/icon/icn_toolbox_bl.png"),
    close: require("../../assets/icon/icn_close_bl.png"),
  },
};

export const LOGO = {
  edit: require("../../assets/icon/logo_edit.png"),
  toolbox: require("../../assets/icon/logo_toolbox.png"),
  stopwatch: require("../../assets/icon/logo_stopwatch.png"),
  hourglass: require("../../assets/icon/logo_hourglass.png"),
  calculator: require("../../assets/icon/logo_calculator.png"),
  info: require("../../assets/icon/logo_info.png"),
  settings: require("../../assets/icon/logo_settings.png"),
  feedback: require("../../assets/icon/logo_feedback.png"),
  options: require("../../assets/icon/logo_options.png"),
  delivering: require("../../assets/icon/logo_delivering.png"),
  legal: require("../../assets/icon/logo_legal.png"),
};
