// Paths of Profile Pictures
export const AVATAR = [
  { path: require("../../assets/image/user/sportif_0.png") },
  { path: require("../../assets/image/user/sportif_1.png") },
  { path: require("../../assets/image/user/sportif_2.png") },
  { path: require("../../assets/image/user/sportif_3.png") },
  { path: require("../../assets/image/user/running_0.png") },
  { path: require("../../assets/image/user/running_1.png") },
  { path: require("../../assets/image/user/running_2.png") },
  { path: require("../../assets/image/user/running_3.png") },
  { path: require("../../assets/image/user/mythical_0.png") },
  { path: require("../../assets/image/user/mythical_1.png") },
  { path: require("../../assets/image/user/mythical_2.png") },
  { path: require("../../assets/image/user/mythical_3.png") },
  { path: require("../../assets/image/user/hallowen_0.png") },
  { path: require("../../assets/image/user/hallowen_1.png") },
  { path: require("../../assets/image/user/hallowen_2.png") },
  { path: require("../../assets/image/user/hallowen_3.png") },
  { path: require("../../assets/image/user/other_0.png") },
  { path: require("../../assets/image/user/other_1.png") },
  { path: require("../../assets/image/user/other_2.png") },
];

export const MUSCLES = [
  { muscle: "arms", source: require("../../assets/image/muscle/arms.png") },
  {
    muscle: "shoulder",
    source: require("../../assets/image/muscle/shoulder.png"),
  },
  { muscle: "abdo", source: require("../../assets/image/muscle/abdo.png") },
  { muscle: "chest", source: require("../../assets/image/muscle/chest.png") },
  { muscle: "back", source: require("../../assets/image/muscle/back.png") },
  { muscle: "buttock", source: require("../../assets/image/muscle/butt.png") },
  { muscle: "thigh", source: require("../../assets/image/muscle/thigh.png") },
  { muscle: "calves", source: require("../../assets/image/muscle/calves.png") },
];

export const ICON = {
  white: {
    remove: require("../../assets/image/icon/white/remove.png"),
    save: require("../../assets/image/icon/white/save.png"),
    add: require("../../assets/image/icon/white/add.png"),
    option: require("../../assets/image/icon/white/option.png"),
    close: require("../../assets/image/icon/white/close.png"),
    home: require("../../assets/image/icon/white/home.png"),
    settings: require("../../assets/image/icon/white/settings.png"),
    toolbox: require("../../assets/image/icon/white/toolbox.png"),
    back: require("../../assets/image/icon/white/back.png"),
    more: require("../../assets/image/icon/white/more.png"),
    send: require("../../assets/image/icon/white/send.png"),
    workout: require("../../assets/image/icon/white/workout.png"),
    search: require("../../assets/image/icon/white/search.png"),
    mail: require("../../assets/image/icon/white/mail.png"),
  },

  black: {
    edit: require("../../assets/image/icon/black/edit.png"),
    nav: require("../../assets/image/icon/black/nav.png"),
    play: require("../../assets/image/icon/black/play.png"),
    shuffle: require("../../assets/image/icon/black/shuffle.png"),
    loop: require("../../assets/image/icon/black/loop.png"),
    finished: require("../../assets/image/icon/black/finished.png"),
    home: require("../../assets/image/icon/black/home.png"),
    settings: require("../../assets/image/icon/black/settings.png"),
    toolbox: require("../../assets/image/icon/black/toolbox.png"),
    close: require("../../assets/image/icon/black/close.png"),
    workout: require("../../assets/image/icon/black/workout.png"),
    timer: require("../../assets/image/icon/black/timer.png"),
    refresh: require("../../assets/image/icon/black/refresh.png"),
    download: require("../../assets/image/icon/black/download.png"),
    upload: require("../../assets/image/icon/black/upload.png"),
  },
};

export const LOGO = {
  edit: require("../../assets/image/logo/edit.png"),
  toolbox: require("../../assets/image/logo/toolbox.png"),
  stopwatch: require("../../assets/image/logo/stopwatch.png"),
  hourglass: require("../../assets/image/logo/hourglass.png"),
  calculator: require("../../assets/image/logo/calculator.png"),
  info: require("../../assets/image/logo/info.png"),
  settings: require("../../assets/image/logo/settings.png"),
  feedback: require("../../assets/image/logo/feedback.png"),
  options: require("../../assets/image/logo/options.png"),
  delivering: require("../../assets/image/logo/delivering.png"),
  legal: require("../../assets/image/logo/legal.png"),
  network_error: require("../../assets/image/logo/network_error.png"),
  muscle: require("../../assets/image/logo/muscle.png"),
  search: require("../../assets/image/logo/search.png"),
  error: require("../../assets/image/logo/error.png"),
  empty: require("../../assets/image/logo/empty.png"),
  workout: require("../../assets/image/logo/workout.png"),
};
