export const SEARCh = [
  {
    uid: "_y5sz022lt",
    description: "",
    title: "Abdominal workout",
    round: "4",
    rest_time: "10",
    final_rest: "120",
    series: [
      {
        uid: "e2f50d5ff_",
        rest: true,
        is_timer: true,
        seriesName: "Hips raise",
        lap: "30",
      },
      {
        uid: "47dcbc95e_",
        rest: true,
        is_timer: true,
        seriesName: "Ciseau",
        lap: "30",
      },
      {
        uid: "34d56dc37_",
        rest: true,
        is_timer: true,
        seriesName: "Knee raise",
        lap: "30",
      },
      {
        uid: "39cd0ed22_",
        rest: true,
        is_timer: true,
        seriesName: "Butterfly",
        lap: "30",
      },
      {
        uid: "a2fb5782c_",
        rest: true,
        is_timer: true,
        seriesName: "Side plank right",
        lap: "30",
      },
      {
        uid: "c23bd49a2_",
        rest: true,
        is_timer: true,
        seriesName: "Side plank left",
        lap: "30",
      },
      {
        uid: "e4de72642_",
        rest: true,
        is_timer: true,
        seriesName: "Push up",
        lap: "30",
      },
      {
        uid: "9137100a8_",
        rest: true,
        is_timer: true,
        seriesName: "Bicycle",
        lap: "30",
      },
    ],
    difficulty: 3,
    muscles: {
      arms: false,
      shoulder: false,
      abdo: true,
      chest: false,
      back: false,
      buttock: false,
      thigh: false,
      calves: false,
    },
    days: [false, false, false, false, false, false, false],
    notification: {
      is_active: false,
      alert_hour: "8",
    },
    publish: {
      published_id: "",
      is_published: false,
      published_at: "",
    },
  },

  {
    uid: "_hwzcd7k2r",
    description: "",
    title: "Lower body workout",
    round: "4",
    final_rest: "60",
    rest_time: "10",
    difficulty: 3,
    muscles: {
      arms: false,
      shoulder: false,
      abdo: false,
      chest: false,
      back: false,
      buttock: true,
      thigh: true,
      calves: true,
    },
    series: [
      {
        uid: "4855cf29d_",
        rest: true,
        is_timer: true,
        seriesName: "Plank",
        lap: "60",
      },
      {
        uid: "cf8ca896b_",
        rest: true,
        is_timer: true,
        seriesName: "Chair",
        lap: "45",
      },
      {
        uid: "12934767e_",
        rest: true,
        is_timer: true,
        seriesName: "Mountain climber",
        lap: "45",
      },
      {
        uid: "0d9a7826f_",
        rest: true,
        is_timer: true,
        seriesName: "Jumping lunge",
        lap: "45",
      },
      {
        uid: "669d71bbb_",
        rest: true,
        is_timer: true,
        seriesName: "Squat",
        lap: "45",
      },
      {
        uid: "618375057_",
        rest: true,
        is_timer: true,
        seriesName: "Donkey kick",
        lap: "45",
      },
    ],
    days: [false, false, false, false, false, false, false],
    notification: {
      is_active: false,
      alert_hour: "8",
    },
    publish: {
      published_id: "",
      is_published: false,
      published_at: "",
    },
  },

  {
    uid: "_jx27lwnw6",
    description: "",
    title: "Complete workout",
    round: "4",
    rest_time: "10",
    final_rest: "120",
    series: [
      {
        uid: "8a2202ade_",
        rest: true,
        is_timer: true,
        seriesName: "Burpee",
        lap: "30",
      },
      {
        uid: "30559cfef_",
        rest: true,
        is_timer: true,
        seriesName: "Jumping",
        lap: "30",
      },
      {
        uid: "ed15a9f33_",
        rest: true,
        is_timer: true,
        seriesName: "Spartan push up",
        lap: "30",
      },
      {
        uid: "39f25b56e_",
        rest: true,
        is_timer: true,
        seriesName: "Abdo crunch",
        lap: "30",
      },
      {
        uid: "33e8346c7_",
        rest: true,
        is_timer: true,
        seriesName: "Air squat",
        lap: "30",
      },
    ],
    difficulty: 3,
    muscles: {
      arms: true,
      shoulder: true,
      abdo: true,
      chest: false,
      back: false,
      buttock: false,
      thigh: true,
      calves: false,
    },
    days: [false, false, false, false, false, false, false],
    notification: {
      is_active: false,
      alert_hour: "8",
    },
    publish: {
      published_id: "",
      is_published: false,
      published_at: "",
    },
  },
];
