export const STORE = [
  {
    days: [false, false, false, false, false, false, false],
    difficulty: 4,
    final_rest: "120",
    notification: {
      alert_hour: "8",
      is_active: false,
    },
    rest_time: "10",
    round: "4",
    series: [
      {
        is_timer: true,
        lap: "45",
        rest: true,
        seriesName: "Burpee",
        uid: "ee54ce750_",
      },
      {
        is_timer: true,
        lap: "45",
        rest: true,
        seriesName: "Fente Sautée",
        uid: "9f6069474_",
      },
      {
        is_timer: true,
        lap: "45",
        rest: true,
        seriesName: "Pompe Spartiate",
        uid: "6bbf59862_",
      },
      {
        is_timer: true,
        lap: "45",
        rest: true,
        seriesName: "Abdo Crunch",
        uid: "236a8e5a6_",
      },
      {
        is_timer: true,
        lap: "45",
        rest: true,
        seriesName: "Air Squat",
        uid: "77ba13f8f_",
      },
    ],
    title: "Entrainement Complets",
    uid: "_5x1irssm2",
  },
  
  {
    days: [false, false, false, false, false, false, false],
    difficulty: 3,
    final_rest: "60",
    notification: {
      alert_hour: "8",
      is_active: false,
    },
    rest_time: "10",
    round: "4",
    series: [
      {
        is_timer: true,
        lap: "60",
        rest: true,
        seriesName: "Gainnage",
        uid: "5f82a6fc4_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Chaise",
        uid: "098f91872_",
      },
      {
        is_timer: true,
        lap: "60",
        rest: true,
        seriesName: "Mountain Climber",
        uid: "2a87ad537_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Fente Sautée",
        uid: "e50494c24_",
      },
      {
        is_timer: true,
        lap: "60",
        rest: true,
        seriesName: "Squat",
        uid: "10b149b5b_",
      },
      {
        is_timer: true,
        lap: "60",
        rest: true,
        seriesName: "Radeaux",
        uid: "cb172f996_",
      },
    ],
    title: "Entrainement Fessiers",
    uid: "_4s387r8am",
  },
  
  {
    days: [false, false, false, false, false, false, false],
    difficulty: 4,
    final_rest: "60",
    notification: {
      alert_hour: "8",
      is_active: false,
    },
    rest_time: "10",
    round: "4",
    series: [
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Hips Raise",
        uid: "d9e4b38c5_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Ciseaux",
        uid: "5bb774396_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Knee Raise",
        uid: "26a565402_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Butterfly",
        uid: "2e483a7d1_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Side Plank Right",
        uid: "e8871ad52_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Side Plank Left",
        uid: "f714cd3a8_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Pompe",
        uid: "83b229c99_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Bicycle",
        uid: "eb8830c13_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Side twist",
        uid: "8dd76a66d_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Rest",
        uid: "ff0fd7fe4_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Toe touches",
        uid: "3a68ed374_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Crunch",
        uid: "373662378_",
      },
      {
        is_timer: true,
        lap: "30",
        rest: true,
        seriesName: "Banane",
        uid: "55ee3f080_",
      },
    ],
    title: "Entrainement abdominal",
    uid: "_w7954co3m",
  },
];
