// Paths of Profile Pictures
export const AVATAR = [
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_sportif_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_running_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_mythical_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_2.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_hallowen_3.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_0.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_1.png") },
  { path: require("../../assets/icon/Profile_Picture/pp_other_2.png") },
];

export const MUSCLES = [
  { muscle: "arms", source: require("../../assets/icon/logo_arms.png") },
  { muscle: "shoulder", source: require("../../assets/icon/logo_shoulder.png") },
  { muscle: "abdo", source: require("../../assets/icon/logo_abdo.png") },
  { muscle: "chest", source: require("../../assets/icon/logo_chest.png") },
  { muscle: "back", source: require("../../assets/icon/logo_back.png") },
  { muscle: "buttock", source: require("../../assets/icon/logo_butt.png") },
  { muscle: "thigh", source: require("../../assets/icon/logo_thigh.png") },
  { muscle: "calves", source: require("../../assets/icon/logo_calves.png") },
];

export const ICON = {
  white: {
    remove: require("../../assets/icon/icn_remove_wh.png"),
    save: require("../../assets/icon/icn_save_wh.png"),
    add: require("../../assets/icon/icn_add_wh.png"),
    option: require("../../assets/icon/icn_option_wh.png"),
    close: require("../../assets/icon/icn_close_wh.png"),
    home: require("../../assets/icon/icn_home_wh.png"),
    settings: require("../../assets/icon/icn_settings_wh.png"),
    store: require("../../assets/icon/icn_store_wh.png"),
    toolbox: require("../../assets/icon/icn_toolbox_wh.png"),
    back: require("../../assets/icon/icn_back_wh.png"),
    more: require("../../assets/icon/icn_more_wh.png"),
    send: require("../../assets/icon/icn_send_wh.png"),
    body: require("../../assets/icon/icn_body_wh.png"),
    workout: require("../../assets/icon/icn_workout_wh.png"),
    expand: require("../../assets/icon/icn_expand_wh.png"),
    publish: require("../../assets/icon/icn_publish_wh.png"),
    search: require("../../assets/icon/icn_search_wh.png"),
  },

  black: {
    edit: require("../../assets/icon/icn_edit_bl.png"),
    nav: require("../../assets/icon/icn_nav_bl.png"),
    play: require("../../assets/icon/icn_play_bl.png"),
    shuffle: require("../../assets/icon/icn_shuffle_bl.png"),
    loop: require("../../assets/icon/icn_loop_bl.png"),
    finished: require("../../assets/icon/icn_finished_bl.png"),
    home: require("../../assets/icon/icn_home_bl.png"),
    settings: require("../../assets/icon/icn_settings_bl.png"),
    store: require("../../assets/icon/icn_store_bl.png"),
    toolbox: require("../../assets/icon/icn_toolbox_bl.png"),
    close: require("../../assets/icon/icn_close_bl.png"),
    workout: require("../../assets/icon/icn_workout_bl.png"),
    timer: require("../../assets/icon/icn_timer_bl.png"),
    refresh: require("../../assets/icon/icn_refresh_bl.png"),
    body: require("../../assets/icon/icn_body_bl.png"),
    download: require("../../assets/icon/icn_download_bl.png"),
    upload: require("../../assets/icon/icn_upload_bl.png"),
  },

  gray: {
    body: require("../../assets/icon/icn_body_gr.png"),
  },
};

export const LOGO = {
  edit: require("../../assets/icon/logo_edit.png"),
  toolbox: require("../../assets/icon/logo_toolbox.png"),
  stopwatch: require("../../assets/icon/logo_stopwatch.png"),
  hourglass: require("../../assets/icon/logo_hourglass.png"),
  calculator: require("../../assets/icon/logo_calculator.png"),
  info: require("../../assets/icon/logo_info.png"),
  settings: require("../../assets/icon/logo_settings.png"),
  feedback: require("../../assets/icon/logo_feedback.png"),
  options: require("../../assets/icon/logo_options.png"),
  delivering: require("../../assets/icon/logo_delivering.png"),
  legal: require("../../assets/icon/logo_legal.png"),
  network_error: require("../../assets/icon/logo_network_error.png"),
  muscle: require("../../assets/icon/logo_muscle.png"),
  bookstore: require("../../assets/icon/logo_bookstore.png"),
  search: require("../../assets/icon/logo_search.png"),
  error: require("../../assets/icon/logo_error.png"),
  empty: require("../../assets/icon/logo_empty.png"),
};
