export const ENGLISH = {
  welcome: "Welcome",
  user_info: "User Information",
  username: "Username",
  profile_picture: "Profile Picture",

  good_morning: "Good Morning",
  good_afternoon: "Good Afternoon",
  good_evening: "Good Evening",

  workout_today: "For today",
  workout_list: "Workout List",
  no_workout_name: "No name",
  duration: "Duration",
  exercice: "Exercice",
  
  title_edit_page: "Edit your workout",
  workout_options: "Workout options",
  workout_name: "Workout name",
  plh_workout_name: "Upper Body Workout",
  round: "Round",
  rest_time: "Rest time",
  final_rest: "Final rest",
  program: "Program",
  plh_series_name: "Your workout name...",
  next_rest: "Nest is rest",
  no_rest: "No rest",
  timer: "Timer",
  new_exercice: "New exercise",
  difficulty: "Difficulty",
  schedule: "Schedule",
  monday_short: "Mon",
  thuesday_short: "Tue",
  wednesday_short: "Wed",
  thursday_short: "Thu",
  friday_short: "Fri",
  saturday_short: "Sat",
  sunday_short: "Sun",
  notification: "Notification",
  recv_notif: "Receive a notification",
  training_hour: "The hour of training",
  warning_notif: "Notifications have been disabled in the app settings.",
  error_notif: "Please allow notifications to be sent, in your phone settings.",
  save: "Save",
  cancel: "Cancel",
  now: "Now",
  next: "Next",
  home: "Home",
  tools: "Tools",
  store: "Store",
  general: "General",
  language: "Language",
  reset: "Reset",
  reset_btn: "Reset the application",
  play: "Play",
  change_button: "Change button",

  alert_unsaved_ttl: "Unsaved changes",
  alert_unsaved_body: "You are about to leave this page without saving your workout.",
  alert_unsaved_stay: "Stay",
  alert_unsaved_leave: "Leave",

  alert_fill_ttl: "Incomplete workout",
  alert_fill_body: "Please complete all exercice fields before starting the workout.",
  alert_fill_btn: "Fill workout",
}

export const FRANCAIS = {
  welcome: "Bienvenue",
  user_info: "Information de l'utilisateur",
  username: "Nom d'utilisateur",
  profile_picture: "Photo de Profile",

  good_morning: "Bonjour",
  good_afternoon: "Bon après-midi",
  good_evening: "Bonsoir",

  workout_today: "Pour aujourd'hui",
  workout_list: "Liste d'entrainement",
  no_workout_name: "Aucun nom",
  duration: "Durée",
  exercice: "Exercice",
  
  title_edit_page: "Modifier votre entrainement",
  workout_options: "Options de l'entrainement",
  workout_name: "Nom de l'entrainement",
  plh_workout_name: "Entrainement haut du corps",
  round: "Tour",
  rest_time: "Repos",
  final_rest: "Dernière pause",
  program: "Programme",
  plh_series_name: "Nom de l'exercice",
  next_rest: "Le prochain est un repos",
  no_rest: "Pas de repos",
  timer: "Chronomètre",
  new_exercice: "Nouvelle exercice",
  difficulty: "Difficultée",
  schedule: "Calendrier",
  monday_short: "Lun",
  thuesday_short: "Mar",
  wednesday_short: "Mer",
  thursday_short: "Jeu",
  friday_short: "Ven",
  saturday_short: "Sam",
  sunday_short: "Dim",
  notification: "Notification",
  recv_notif: "Recevoir une notification",
  training_hour: "L'heure d'entrainement",
  warning_notif: "Les notifications ont été désactivé dans les paramètre de l'application.",
  error_notif: "Veuillez autoriser l'envoie de notification dans vos paramètres de téléphone.",
  save: "Sauvegarder",
  cancel: "Annuler",
  now: "Maintenant",
  next: "Suivant",
  home: "Page d'accueil",
  tools: "Outils",
  store: "Magasin",
  general: "Generale",
  language: "Langage",
  reset: "Réinitialiser",
  reset_btn: "Réinitialiser l'application",
  play: "Commencer",
  change_button: "Changer les boutons",

  alert_unsaved_ttl: "Modifications non enregistrées",
  alert_unsaved_body: "Vous êtes sur le point de quitter cette page sans enregistrer vos modifications.",
  alert_unsaved_stay: "Rester",
  alert_unsaved_leave: "Quitter",

  alert_fill_ttl: "Entrainement incompleté",
  alert_fill_body: "Veuillez compléter votre entrainement avant de commencer l'entraînement.",
  alert_fill_btn: "Compléter l'entrainement",
}